AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AI Product Description Generator - Core Services

Globals:
  Function:
    Timeout: 30 # Default timeout for all functions
    MemorySize: 128 # Default memory for all functions

Parameters:
  ProductDescriptionExportsBucketName:
    Type: String
    Default: product-description-artifacts-882961643245

Resources:
  GenerateDescriptionLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: product_generator.lambda_handlers.generate_description_lambda.lambda_handler
      Runtime: python3.11
      CodeUri: src/
      MemorySize: 128
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            Effect: Allow
            Action:
              - bedrock:InvokeModel
            Resource: "*"
      Events:
        GenerateDescriptionApi:
          Type: HttpApi
          Properties:
            Path: /generate
            Method: post
      Environment:
        Variables:
          STORE_DESCRIPTION_LAMBDA_ARN: !GetAtt StoreDescriptionLambda.Arn

  ProductDescriptionsTable:
    Type: AWS::DynamoDB::Table 
    Properties:
      TableName: ProductDescriptions
      AttributeDefinitions:
        - AttributeName: productId
          AttributeType: S 
        - AttributeName: formatType
          AttributeType: S
      KeySchema:
        - AttributeName: productId
          KeyType: HASH 
        - AttributeName: formatType
          KeyType: RANGE 
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  StoreDescriptionLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: product_generator.lambda_handlers.store_description_lambda.lambda_handler
      Runtime: python3.11
      CodeUri: src/
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          PRODUCT_DESCRIPTIONS_TABLE: !Ref ProductDescriptionsTable
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductDescriptionsTable

  ExportDescriptionLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: product_generator.lambda_handlers.export_description_lambda.lambda_handler
      Runtime: python3.11
      CodeUri: src/
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          PRODUCT_DESCRIPTIONS_TABLE: !Ref ProductDescriptionsTable
          EXPORTS_S3_BUCKET: !Ref ProductDescriptionExportsBucketName
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBReadPolicy:
            TableName: !Ref ProductDescriptionsTable
        - S3WritePolicy:
            BucketName: !Ref ProductDescriptionExportsBucketName
      Events:
        ExportDescriptionApi:
          Type: HttpApi
          Properties:
            Path: /export-csv
            Method: get

  GenerateDescriptionLambdaErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "Alarm for GenerateDescriptionLambda encounters errors"
      AlarmName: !Sub "${AWS::StackName}-GenerateDescriptionLambda-Errors"
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 0
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      Dimensions:
        - Name: FunctionName
          Value: !Ref GenerateDescriptionLambda


Outputs:
  GenerateDescriptionApi: 
    Description: "ARN of the GenerateDescriptionLambda function"
    Value: !GetAtt GenerateDescriptionLambda.Arn
    Export: 
      Name: GenerateDescriptionLambdaArn

  ProductDescriptionTableName:
    Description: "Name of the DynamoDB table for product descriptions"
    Value: !Ref ProductDescriptionsTable
    Export:
      Name: ProductDescriptionTableName

  StoreDescriptionLambdaArn:
    Description: "ARN of the StoreDescriptionLambda function"
    Value: !GetAtt StoreDescriptionLambda.Arn
    Export:
      Name: StoreDescriptionLambdaArn

  ProductDescriptionExportsBucket:
    Description: "Name of the S3 bucket for product description exports"
    Value: !Ref ProductDescriptionExportsBucketName
    Export:
      Name: ProductDescriptionExportsBucketName

  ExportDescriptionLambdaArn:
    Description: "ARN of the ExportDescriptionLambda function"
    Value: !GetAtt ExportDescriptionLambda.Arn
    Export:
      Name: ExportDescriptionLambdaArn

  ExportDescriptionApi:
    Description: "API Gateway endpoint URL for ExportDescriptionLambda"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/export-csv"
    Export:
      Name: ExportDescriptionApi
