name: Deploy Serverless Application

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-2
  SAM_STACK_NAME: product-description-generator 
  S3_BUCKET_NAME: product-description-artifacts-882961643245

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write 
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install SAM CLI
          pip install aws-sam-cli
          # Install project dependencies (from src/requirements.txt)
          pip install -r src/requirements.txt
          # Install dev dependencies for testing (pytest, pytest-mock)
          pip install pytest pytest-mock

      - name: Run unit tests
        run: AWS_REGION=us-east-2 pytest tests/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: SAM Build
        run: sam build --template template.yaml --cached

      - name: SAM Deploy
        run: |
          sam deploy \
            --stack-name ${{ env.SAM_STACK_NAME }} \
            --region ${{ env.AWS_REGION }} \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --s3-bucket ${{ env.S3_BUCKET_NAME }}

